# Numpy
几个性质：
* numpy默认的类型是64位浮点数

In [1]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
b = np.zeros_like(a) # 创建一个与a形状相同的0数组
b

array([0, 0, 0])

In [7]:
c = np.ones((3,4))
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
d = np.arange(3,8) #创建递增数组
d

array([3, 4, 5, 6, 7])

In [14]:
# 创建介于某个区间，等间距的数组
e = np.linspace(1,10,5) # 第一第二个参数是范围，第三个是输出样本的总数
e

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
f = np.random.rand(5) # 随机数
f

array([0.89612888, 0.57943021, 0.37446268, 0.9311481 , 0.66542435])

In [18]:
# 修改数据类型
g = np.zeros((4,2),dtype=np.int32)
g

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [19]:
# 对于现有的数组，也可以通过astype转换
f = f.astype(np.int32)
f

array([0, 0, 0, 0, 0], dtype=int32)

## 数组运算

In [21]:
# 1. 加减乘除
# 会进行同位置加减乘除运算
a = np.array([1,2,3])
b = np.array([4,5,6])

a+b,a-b,a*b,b/a

(array([5, 7, 9]),
 array([-3, -3, -3]),
 array([ 4, 10, 18]),
 array([4. , 2.5, 2. ]))

In [22]:
# 2.点乘运算
c = np.dot(a,b)
c

32

In [37]:
# 3. 矩阵乘法——使用@符
a = np.random.randint(1,10,(5,5))
b = np.random.randint(1,10,(5,5))
a@b

array([[ 81, 193, 201, 120, 173],
       [ 76, 126, 128,  80, 132],
       [ 82, 135, 122,  83, 141],
       [ 80, 137, 166, 125, 136],
       [ 62, 117, 132, 103, 106]])

In [40]:
# 或者使用multmul
c = np.matmul(a,b)
c

array([[ 81, 193, 201, 120, 173],
       [ 76, 126, 128,  80, 132],
       [ 82, 135, 122,  83, 141],
       [ 80, 137, 166, 125, 136],
       [ 62, 117, 132, 103, 106]])

In [46]:
# 4.求平方根
a = np.random.randint(1,10,(5,5))
print(a)
np.sqrt(a)

[[2 2 5 8 3]
 [7 8 5 5 7]
 [5 7 6 5 4]
 [1 6 4 7 7]
 [3 5 8 7 8]]


array([[1.41421356, 1.41421356, 2.23606798, 2.82842712, 1.73205081],
       [2.64575131, 2.82842712, 2.23606798, 2.23606798, 2.64575131],
       [2.23606798, 2.64575131, 2.44948974, 2.23606798, 2.        ],
       [1.        , 2.44948974, 2.        , 2.64575131, 2.64575131],
       [1.73205081, 2.23606798, 2.82842712, 2.64575131, 2.82842712]])

In [48]:
print(b)
np.sin(b)

[[3 9 8 8 4]
 [3 9 6 1 9]
 [1 1 9 3 4]
 [5 5 1 4 4]
 [3 4 7 4 7]]


array([[ 0.14112001,  0.41211849,  0.98935825,  0.98935825, -0.7568025 ],
       [ 0.14112001,  0.41211849, -0.2794155 ,  0.84147098,  0.41211849],
       [ 0.84147098,  0.84147098,  0.41211849,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.95892427,  0.84147098, -0.7568025 , -0.7568025 ],
       [ 0.14112001, -0.7568025 ,  0.6569866 , -0.7568025 ,  0.6569866 ]])